# 1. Build Image
FROM golang:1.13 AS builder
 
# Install dependencies
WORKDIR /go/src/github.com/asashiho/dockertext-greet
RUN go get -d -v github.com/urfave/cli
 
# Build modules
COPY main.go main.go
RUN GOOS=linux go build -a -o greet main.go

# 실행
ENTRYPOINT ["./greet"]
